@ echo off
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com
start "" https://www.roblox.com